// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebbsmxqcqbefktdqksex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImViYnNteHFjcWJlZmt0ZHFrc2V4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NDA0NzIsImV4cCI6MjA3MjMxNjQ3Mn0.y3Hlx7DnzjrmGc2py7L7_9Ycw8pQCWEnC_Xzz3Cjv8s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});